(use-modules (plotutils plot))

(define plotter-params (newplparams))
(setplparam! plotter-params "PAGESIZE" "letter")
(define plotter (newpl "X" (current-output-port) (current-error-port) plotter-params))
(openpl! plotter)
(space! plotter 0.0 0.0 1000.0 1000.0)
(linewidth! plotter 5.0)
(pencolorname! plotter "green")
(fillcolorname! plotter "light blue")
(filltype! plotter 1)
(erase! plotter)
(orientation! plotter 1)
(box! plotter 50.0 50.0 950.0 950.0)
(endsubpath! plotter)
(let loop ((i 0))
  (let loop2 ((j 9))
    (orientation! plotter (if (= 0 (modulo j 2))
			      -1
			      1))
    (circle! plotter (+ 250.0 (* 500.0 i)) 500.0 (* j 20.0))
    (endsubpath! plotter)
    (if (>= j 3)
	(loop2 (- j 1))))
  (move! plotter (+ 225.0 (* i 500.0)) 475.0)
  (cont! plotter (+ 250.0 (* i 500.0)) 525.0)
  (cont! plotter (+ 275.0 (* i 500.0)) 475.0)
  (endsubpath! plotter)
  (if (< i 2)
      (loop (+ i 1))))
(endpath! plotter)
(closepl! plotter)
