name: Ubuntu 24.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEBIAN_FRONTEND: noninteractive
  TZ: America/Los_Angeles

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y guile-3.0-dev texlive texlive-plain-generic plotutils libplot-dev

    - name: Configure
      run: |
        autoreconf -vif
        ./configure --prefix="$(pwd)/dist" 2>&1 | tee config.log

    - name: Build
      run: make 2>&1 | tee build.log

    - name: Test
      run: make check 2>&1 | tee test.log
      shell: bash {0}

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: logs
        path: |
          config.log
          build.log
          test.log
